# all dimensions
all_dims = [
    "text_id",
    "user_id",
    "Pozytywne",
    "Negatywne",
    "Radość",
    "Zachwyt",
    "Inspiruje",
    "Spokój",
    "Zaskoczenie",
    "Współczucie",
    "Strach",
    "Smutek",
    "Wstręt",
    "Złość",
    "Ironiczny",
    "Żenujący",
    "Wulgarny",
    "Polityczny",
    "Interesujący",
    "Zrozumiały",
    "Zgadzam się z tekstem",
    "Wierzę w tę informację",
    "Potrzebuję więcej informacji, aby ocenić ten tekst",
    "Czuję sympatię do autora",
    "Obraża mnie",
    "Może kogoś atakować / obrażać / lekceważyć",
    "Mnie bawi/śmieszy?",
    "Może kogoś bawić?",
]

condition_label_dims = {
    "Może kogoś bawić?": "Mnie bawi/śmieszy?",
    "Może kogoś atakować / obrażać / lekceważyć": "Obraża mnie",
}

label_dims = [
    "Pozytywne",
    "Negatywne",
    "Radość",
    "Zachwyt",
    "Inspiruje",
    "Spokój",
    "Zaskoczenie",
    "Współczucie",
    "Strach",
    "Smutek",
    "Wstręt",
    "Złość",
    "Ironiczny",
    "Żenujący",
    "Wulgarny",
    "Polityczny",
    "Interesujący",
    "Zrozumiały",
    "Potrzebuję więcej informacji, aby ocenić ten tekst",
    "Obraża mnie",
    "Może kogoś atakować / obrażać / lekceważyć",
    "Mnie bawi/śmieszy?",
    "Może kogoś bawić?",
]

dimension_splits = []
# all dimensions without text_id and user_id
all_dims_no_id = [
    "Pozytywne",
    "Negatywne",
    "Radość",
    "Zachwyt",
    "Inspiruje",
    "Spokój",
    "Zaskoczenie",
    "Współczucie",
    "Strach",
    "Smutek",
    "Wstręt",
    "Złość",
    "Ironiczny",
    "Żenujący",
    "Wulgarny",
    "Polityczny",
    "Interesujący",
    "Zrozumiały",
    "Zgadzam się z tekstem",
    "Wierzę w tę informację",
    "Potrzebuję więcej informacji, aby ocenić ten tekst",
    "Czuję sympatię do autora",
    "Obraża mnie",
    "Może kogoś atakować / obrażać / lekceważyć",
    "Mnie bawi/śmieszy?",
    "Może kogoś bawić?",
]

# excluded dimensions
excluded_dims = [
    "Czuję sympatię do autora",
    "Wierzę w tę informację",
    "Zgadzam się z tekstem",
    "Obraża mnie",
    "Mnie bawi/śmieszy?",
]
